FROM golang:1.24-alpine AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 go build -o signer-proxy .

FROM ubuntu:24.04
COPY --from=builder /app/signer-proxy /
ENTRYPOINT ["/signer-proxy"]
